### ISSUE TITLE
source mentions include file geo_lib.h

### ISSUE THREAD

**Issue by csrabak** [HansWessels/geolib#1]
In line 20 of geo_lib.c there is an include to geo_lib.h

Is this file available or is it supposed to create it from the contents of the .c source?

TIA

**Comment by HansWessels** [comment]
It should have been included.
The contents are:
/*
**
** geo_lib
** copy left 2016 Hans Wessels
** This code is placed in public domain by Hans Wessels
**
** library for conversion of coordinate systems and pretty printing of coordinates
**
*/

#ifndef __geo_lib__
#define __geo_lib__

#include <math.h>
#include <stdio.h>

int xy2ne(double* n, double* e, double x, double y); /* RD to WGS84 conversion */
int ne2xy(double* x, double* y, double n, double e); /* WGS84 to RD conversion */
char* nddd_str(char* str, double n); /* double n to Ndd.ddddd string, length of str is at least 10 */
char* eddd_str(char* str, double e); /* double e to Eddd.ddddd string, length of str is at least 11 */
char* ddd_str(char* str, double n, double e); /* double n, e to Ndd.ddddd Eddd.ddddd string, length of str is at least 21 */
char* ndmm_str(char* str, double n); /* double n to Ndd mm.mmm string, length of str is at least 11 */
char* edmm_str(char* str, double e); /* double e to Eddd mm.mmm string, length of str is at least 12 */
char* dmm_str(char* str, double n, double e); /* double n, e to Ndd mm.mmm Eddd mm.mmm string, length of str is at least 23 */
char* ndms_str(char* str, double n); /* double n to Ndd mm'ss.ss" string, length of str is at least 14 */
char* edms_str(char* str, double e); /* double e to Eddd mm'ss.ss" string, length of str is at least 15 */
char* dms_str(char* str, double n, double e); /* double n, e to Ndd mm'ss.ss" Eddd mm'ss.ss" string, length of str is at least 29 */
char* xxx_str(char* str, double x); /* double x to X:xxxxxxm, length of str is at least 10 */
char* yyy_str(char* str, double y); /* double y to Y:yyyyyym, length of str is at least 10 */
char* xy_str(char* str, double x, double y); /* double x, y to X:xxxxxxm Y:yyyyyym, length of str is at least 20 */

FILE* fopen_kml(char* filename); /* opens filename and initializes it for kml ponits */
int fprint_placemark(FILE* f, double n, double e, char* name, char* description); /* print coordinates with name and description in kml file */
int fclose_kml(FILE* f); /* closes kml file */

#endif

**Comment by HansWessels** [comment]
`/*
**
** geo_lib
** copy left 2016 Hans Wessels
** This code is placed in public domain by Hans Wessels
**
** library for conversion of coordinate systems and pretty printing of coordinates
**
*/

#ifndef __geo_lib__
#define __geo_lib__

#include <math.h>
#include <stdio.h>

int xy2ne(double* n, double* e, double x, double y); /* RD to WGS84 conversion */
int ne2xy(double* x, double* y, double n, double e); /* WGS84 to RD conversion */
char* nddd_str(char* str, double n); /* double n to Ndd.ddddd string, length of str is at least 10 */
char* eddd_str(char* str, double e); /* double e to Eddd.ddddd string, length of str is at least 11 */
char* ddd_str(char* str, double n, double e); /* double n, e to Ndd.ddddd Eddd.ddddd string, length of str is at least 21 */
char* ndmm_str(char* str, double n); /* double n to Ndd mm.mmm string, length of str is at least 11 */
char* edmm_str(char* str, double e); /* double e to Eddd mm.mmm string, length of str is at least 12 */
char* dmm_str(char* str, double n, double e); /* double n, e to Ndd mm.mmm Eddd mm.mmm string, length of str is at least 23 */
char* ndms_str(char* str, double n); /* double n to Ndd mm'ss.ss" string, length of str is at least 14 */
char* edms_str(char* str, double e); /* double e to Eddd mm'ss.ss" string, length of str is at least 15 */
char* dms_str(char* str, double n, double e); /* double n, e to Ndd mm'ss.ss" Eddd mm'ss.ss" string, length of str is at least 29 */
char* xxx_str(char* str, double x); /* double x to X:xxxxxxm, length of str is at least 10 */
char* yyy_str(char* str, double y); /* double y to Y:yyyyyym, length of str is at least 10 */
char* xy_str(char* str, double x, double y); /* double x, y to X:xxxxxxm Y:yyyyyym, length of str is at least 20 */

FILE* fopen_kml(char* filename); /* opens filename and initializes it for kml ponits */
int fprint_placemark(FILE* f, double n, double e, char* name, char* description); /* print coordinates with name and description in kml file */
int fclose_kml(FILE* f); /* closes kml file */

#endif`

**Comment by HansWessels** [comment]
Warning: the 'smart' interpretation ate soem *'s and '_', even in code mode. I couldn't attache the file as an zip file either.

sigh...

**Comment by csrabak** [comment]
I understand these hurdles... being there done that more than a time...

TKS for reply!
